Repository Zakarya525/toDoApp, pull requests merged in 2022-10, with the labels that each got.

#11 Feature/drawer with logout
  App.js
  package-lock.json
  package.json
  src/components/Body/Body.js
  src/components/Body/Styles.js
  src/components/Card/Card.js
  src/components/Card/CardBody.js
  src/components/Card/CardHeader.js
  src/components/Card/CardItem.js
  src/components/Drawer/DrawerContent.js
  src/components/Drawer/Style.js
  src/components/Header/DashHeader.js
  src/components/Header/Header.js
  src/components/Header/HeaderText.js
  src/components/Header/HeaderTitle.js
  src/components/Loading/Loading.js
  src/components/ProfileImage/ProfileImage.js
  src/components/StatusBar/CustomStatusBar.js
  src/components/StatusBar/index.js
  src/config/theme.js
  src/context/Authentication/AuthProvider.js
  src/context/Authentication/authReducer.js
  src/context/Authentication/index.js
  src/context/Theme/ThemeProvider.js
  src/context/Theme/index.js
  src/context/Theme/themeContext.js
  src/context/Theme/themeReducer.js
  src/navigations/DrawerNavigation.js
  src/navigations/StackNavigation.js
  src/screens/Dashboard.js
  src/screens/Login.js
  src/screens/Register.js
  src/storage/index.js
Labels: feature

#15 remove react-native-community and eslint package
  package-lock.json
Labels: enhancement

#16 expo-splash-screen added
  App.js
  package-lock.json
  package.json
Labels: enhancement

#17 forms-validation added
  package-lock.json
  package.json
  src/components/Card/CardHeader.js
  src/screens/Login.js
  src/screens/Register.js
  src/screens/Styles.js
  src/utils/colors.js
Labels: feature, Ready for Review
